name: fams
dependencies:
  - python=3.8
  - pip
  - pip:
    - torch==2.1
    - torchvision
    - diffusers==0.25.0
    - transformers
    - accelerate
    - ftfy
    - tensorboard
    - datasets
    - xformers
    - bitsandbytes
    - ipykernel