name: face-anon-simple
dependencies:
  - python=3.9
  - pip
  - pip:
    - torch==2.2
    - torchvision==0.17.0
    - huggingface_hub<0.26.0
    - diffusers==0.25.1
    - transformers==4.37.2
    - accelerate==0.27.2
    - datasets==2.17.0
    - xformers==0.0.24
    - bitsandbytes==0.42.0
    - ipykernel==6.29.5
    - face-alignment==1.4.1
