name: face-anon-simple
dependencies:
  - python=3.8
  - pip
  - pip:
    - torch==2.1
    - torchvision
    - huggingface_hub<0.26.0
    - diffusers==0.25.0
    - transformers
    - accelerate
    - ftfy
    - tensorboard
    - datasets
    - xformers
    - bitsandbytes
    - ipykernel
    - face-alignment
